### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by mjseok** [mjseok/Tripful#35]
# ✅ 체크 리스트

우선순위 순

### 12/5 오후 6시까지 완성하고 만나기 
- [x] #36
- [x] #40
- [ ] 리뷰기능
- [ ] 스케줄 페이지
--- 
- [ ] #42
- [ ] 자세한 관광지 페이지 지도 추가
- [ ] 비밀번호 찾기 (이메일로 보내주기)
- [ ] 깃헙 로그인
- [ ] 카카오 로그인
- [ ] 게시판 파일 추가
- [ ] 게시판 댓글
---
- [ ] index 페이지
## 오류 수정 (26일 ~ 31일)

- [ ] 관광지 변경 시 infoWindow 남아있음 + 관광지 검색 리스트 초기화
- [ ] 코드 개선(REST하게 바꾸기)

## 배포 (마지막)
- [ ] 배포

**Comment by tykwon97** [comment]
좋아요

**Comment by tykwon97** [comment]
https://www.notion.so/4711c3a2041741c29fe62f257f901ed2?v=9fa0bb58254040808c115c5e4a5951fb
